ruby '1.9.3'
source 'https://rubygems.org'
gem 'rails'
gem 'rack'
gem 'thin'
gem 'rack-cache', :require => 'rack/cache'
gem 'json', :require => 'json'
gem 'sinatra', :require => 'sinatra/base'
gem 'sinatra-contrib', :require => 'sinatra/json'
gem 'newrelic_rpm'
